// ignore_for_file: constant_identifier_names

// Menu
const int BACKGROUND_COLOR = 0xFFE8E6E9;
const int JOIN_GAME_BUTTON_COLOR = 0xFFF2226E;
const int NEW_GAME_BUTTON_COLOR = 0xFF36C6AF;
const int PVP_BUTTON_COLOR = 0xFFF8CE2C;
const int ESCAPE_BUTTON_COLOR = 0xFFB332A6;

// Lobby
const int START_GAME_BUTTON_COLOR = 0xFFB332A6;
const int SPECTATE_BUTTON_COLOR = 0xFF36C6AF;

// Maze
const int WALL_COLOR = 0xFF7A4B82;
const int RED_BORDER_COLOR = 0xFFF2226E;
const int MAZE_BACKGROUND_COLOR = 0xFFFFFFFF;
