name: Backend CI/CD

on:
  push:
    branches: [ "main" ]
    paths:
      - backend/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            ls
            cd /home/yuna/attention
            
            # Pull from git repo
            git checkout main || true # Force return true so exit code is not 1
            git pull
            
            # Backend CD
            cd backend
            export PATH="$PATH:/home/yuna/.nvm/versions/node/v18.13.0/bin"
            killall node || true # Force return true so exit code is not 1
            yarn install
            nohup yarn prod > nohup.out 2> nohup.err < /dev/null &
            
